name: End-to-end tests
on: [push]
jobs:
  vite-cli-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./create-test-app.sh "npm create vite@latest test-app -- --template vue"
      - uses: cypress-io/github-action@v6
        with:
          start: npm run test:preview
