name: End-to-end tests
on: [push]
jobs:
  vite-cli-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./create-test-app.sh "npm create vite@latest test-app -- --template vue"
      - uses: cypress-io/github-action@v6
        with:
          start: npm run test:preview

  vite-cli-latest-ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./create-test-app.sh "npm create vite@latest test-app -- --template vue-ts" --typescript
      - uses: cypress-io/github-action@v6
        with:
          start: npm run test:preview

  vite-cli-4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./create-test-app.sh "npm create vite@4 test-app -- --template vue"
      - uses: cypress-io/github-action@v6
        with:
          start: npm run test:preview

  vite-cli-4-ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./create-test-app.sh "npm create vite@4 test-app -- --template vue-ts" --typescript
      - uses: cypress-io/github-action@v6
        with:
          start: npm run test:preview

  vue-cli-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./create-test-app.sh "npm create vue@latest test-app -- --default"
      - uses: cypress-io/github-action@v6
        with:
          start: npm run test:preview

  vue-cli-latest-ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./create-test-app.sh "npm create vue@latest test-app -- --default --ts" --typescript
      - uses: cypress-io/github-action@v6
        with:
          start: npm run test:preview
