name: End-to-end tests
on: [push]
jobs:
  vite-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm create vite@latest test-app -- --template vue-ts
      - run: | 
          mv ./example/src/App.vue ./test-app/src/App.vue
          mv ./example/vite.config.ts ./test-app/vite.config.ts
          mv ./example/src/vite-env.d.ts ./test-app/src/vite-env.d.ts
          mv ./example/src/assets ./test-app/src/assets
          mv ./example/public ./test-app/public
      - run: | 
          cd test-app
          npm install
          npm install vite-svg-loader --save-dev
      - uses: cypress-io/github-action@v6
        with:
          working-directory: test-app
          build: npm run build
          start: npm run preview
