name: End-to-end tests
on: [push]
jobs:
  vite-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm create vite@latest test-app -- --template vue-ts
      - run: | 
          mv ./example/src/App.vue ./test-app/src/App.vue
          mv ./example/vite.config.ts ./test-app/vite.config.ts
          mv ./example/src/vite-env.d.ts ./test-app/src/vite-env.d.ts
          mv ./example/src/assets/test.svg ./test-app/src/assets/test.svg
          mv ./example/src/assets/style.svg ./test-app/src/assets/style.svg
          mv ./example/src/assets/circle.svg ./test-app/src/assets/circle.svg
          mv ./example/public/root.svg ./test-app/public/root.svg
      - run: | 
          cd test-app
          npm install
          npm install vite-svg-loader --save-dev
      - uses: cypress-io/github-action@v6
        with:
          build: cd test-app && npm run build
          start: cd test-app && npm run preview
