name: End-to-end tests
on: [push]
jobs:
  vite-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm create vite@latest test-app -- --template vue-ts
      - run: mv ./example/App.vue ./test-app/App.vue
      - run: mv ./example/vite.config.ts ./test-app/vite.config.ts
      - run: mv ./example/assets ./test-app/assets
      - run: mv ./example/public ./test-app/public
      - run: cd test-app
      - run: npm install
      - run: npm install vite-svg-loader --save-dev
      - run: npm build
      - run: npm preview
      - uses: cypress-io/github-action@v6
